using System.Collections;
using System.Collections.Generic;

public class DeckDataBase{
	 public static List<SkillData> PLAYER_DECK = new List<SkillData>(){
		//  SkillDataBase.SKILL_DATAS[SKILL_NAME.SPINKICK_GREEN_BASE_FIGHTER.ToString()],
		//  SkillDataBase.SKILL_DATAS[SKILL_NAME.SPINKICK_GREEN_CHASE1_FIGHTER.ToString()],
		//  SkillDataBase.SKILL_DATAS[SKILL_NAME.SPINKICK_GREEN_CHASE2_FIGHTER.ToString()],

		/*赤・パンチ　初動　*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.JAB_RED_BASE_FIGHTER.ToString()],
		/*赤・パンチ　追撃１*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.JAB_RED_CHASE1_FIGHTER.ToString()],
		/*青・キック　初動　*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.HIKICK_BLUE_BASE_FIGHTER.ToString()],
		/*青・キック　追撃１*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.HIKICK_BLUE_CHASE1_FIGHTER.ToString()],
		/*青・キック　追撃２*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.HIKICK_BLUE_CHASE2_FIGHTER.ToString()],
		/*緑・スピンキック　追撃１*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.SPINKICK_GREEN_CHASE1_FIGHTER.ToString()],
		/*緑・スピンキック　追撃２*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.SPINKICK_GREEN_CHASE2_FIGHTER.ToString()],
		/*青・剣突き　初動　*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.SWORD_THRUST_BLUE_BASE_SWORDMAN.ToString()],
		/*青・剣突き　追撃１*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.SWORD_THRUST_BLUE_CHASE1_SWORDMAN.ToString()],
		/*緑・剣斬り　初動　*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.SWORD_SLASH_GREEN_BASE_SWORDMAN.ToString()],
		/*緑・剣斬り　追撃１*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.SWORD_SLASH_GREEN_CHASE1_SWORDMAN.ToString()],
		/*緑・剣斬り　追撃２*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.SWORD_SLASH_GREEN_CHASE2_SWORDMAN.ToString()],
		/*赤・剣大振り　追撃１*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.SWORD_SWIND_RED_CHASE1_SWORDMAN.ToString()],
		/*赤・剣大振り　追撃２*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.SWORD_SWIND_RED_CHASE2_SWORDMAN.ToString()],

		/*赤・パンチ　初動　*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.JAB_RED_BASE_FIGHTER.ToString()],
		/*赤・パンチ　追撃１*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.JAB_RED_CHASE1_FIGHTER.ToString()],
		/*青・キック　初動　*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.HIKICK_BLUE_BASE_FIGHTER.ToString()],
		/*緑・スピンキック　追撃２*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.SPINKICK_GREEN_CHASE2_FIGHTER.ToString()],
		/*無色 ガード　*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.GUARD.ToString()],
		/*無色 ガード　*/ SkillDataBase.SKILL_DATAS[SKILL_NAME.GUARD.ToString()],
	 };

	 public static List<SkillData> ENEMY_DECK = new List<SkillData>(){
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.JAB_RED_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.JAB_RED_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.JAB_RED_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.JAB_RED_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.JAB_RED_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.JAB_RED_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.JAB_RED_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.JAB_RED_BASE_FIGHTER.ToString()],

		 SkillDataBase.SKILL_DATAS[SKILL_NAME.HIKICK_BLUE_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.HIKICK_BLUE_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.HIKICK_BLUE_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.HIKICK_BLUE_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.HIKICK_BLUE_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.HIKICK_BLUE_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.HIKICK_BLUE_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.HIKICK_BLUE_BASE_FIGHTER.ToString()],

		 SkillDataBase.SKILL_DATAS[SKILL_NAME.SPINKICK_GREEN_BASE_FIGHTER.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.SPINKICK_GREEN_BASE_FIGHTER.ToString()],
		 //SkillDataBase.SKILL_DATAS[SKILL_NAME.SPINKICK_GREEN_BASE_FIGHTER.ToString()],
		 //SkillDataBase.SKILL_DATAS[SKILL_NAME.SPINKICK_GREEN_BASE_FIGHTER.ToString()],
		 //SkillDataBase.SKILL_DATAS[SKILL_NAME.SPINKICK_GREEN_BASE_FIGHTER.ToString()],
		 //SkillDataBase.SKILL_DATAS[SKILL_NAME.SPINKICK_GREEN_BASE_FIGHTER.ToString()],

		 SkillDataBase.SKILL_DATAS[SKILL_NAME.GUARD.ToString()],
		 SkillDataBase.SKILL_DATAS[SKILL_NAME.GUARD.ToString()],
	 };
}